name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 안드로이드 SDK 라이선스 자동 동의 및 빌도저 필수 도구 전면 추가
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev libgdbm-dev libreadline-dev libffi-dev uuid-dev ccache
        pip install --upgrade pip setuptools
        pip install "cython<3.0.0" buildozer python-for-android

    - name: Configure PIP
      run: |
        mkdir -p ~/.config/pip
        echo -e "[global]\nuser = false" > ~/.config/pip/pip.conf

    # 🚀 깃허브 가상 컴퓨터가 멈추지 않도록 자동 동의 환경변수를 먹이고 빌드 가동
    - name: Build APK with Buildozer
      env:
        APP_ANDROID_ACCEPT_SDK_LICENSE: "y"
      run: |
        buildozer android debug
