name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # 가장 안정적으로 빌도저 환경을 격리해 실행해주는 검증된 액션 도입
    - name: Build APK with Buildozer Action
      uses: RobertPhan/buildozer-action@v1.3
      with:
        buildozer_version: stable
        command: buildozer android debug
        repository_root: .

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
